version: "3.0"
services:
    mysql:
        image: mysql:5.5
        ports:
            - 23306:3306
        volumes:
            - ./etc/db:/docker-entrypoint-initdb.d
            - ./etc/my.cnf:/etc/mysql/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=kuki